# Generated by Django 5.0.6 on 2024-06-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=50, verbose_name='Name')),
                ('body', models.CharField(blank=True, max_length=200, null=True, verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DataTime')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.DeleteModel(
            name='POST_MODEL',
        ),
    ]
